WARNING 2018-08-24 00:23:42,050 base 14574 123145490411520 Not Found: /struts2-rest-showcase/orders.xhtml
WARNING 2018-08-24 00:23:42,051 basehttp 14574 123145490411520 "GET /struts2-rest-showcase/orders.xhtml HTTP/1.1" 404 3011
WARNING 2018-08-24 00:23:42,227 base 14574 123145490411520 Not Found: /index.action
WARNING 2018-08-24 00:23:42,227 basehttp 14574 123145490411520 "GET /index.action HTTP/1.1" 404 2945
WARNING 2018-08-24 00:23:42,404 base 14574 123145490411520 Not Found: /index.do
WARNING 2018-08-24 00:23:42,405 basehttp 14574 123145490411520 "GET /index.do HTTP/1.1" 404 2933
WARNING 2018-08-24 00:27:40,964 base 14574 123145490411520 Not Found: /struts2-rest-showcase/orders.xhtml
WARNING 2018-08-24 00:27:40,965 basehttp 14574 123145490411520 "GET /struts2-rest-showcase/orders.xhtml HTTP/1.1" 404 3011
WARNING 2018-08-24 00:27:41,148 base 14574 123145490411520 Not Found: /index.action
WARNING 2018-08-24 00:27:41,149 basehttp 14574 123145490411520 "GET /index.action HTTP/1.1" 404 2945
WARNING 2018-08-24 00:27:41,312 base 14574 123145490411520 Not Found: /index.do
WARNING 2018-08-24 00:27:41,313 basehttp 14574 123145490411520 "GET /index.do HTTP/1.1" 404 2933
INFO 2018-08-24 22:35:49,893 basehttp 23830 123145561661440 "GET /view/task/5b5f02a4421aa9031208072c HTTP/1.1" 301 0
ERROR 2018-08-24 22:35:49,933 exception 23830 123145566916608 Internal Server Error: /view/task/5b5f02a4421aa9031208072c/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bcj/Documents/科技部/EItools/EItools/crawler/task.py", line 41, in get_task_by_id
    return HttpResponse(json.dumps(result), content_type="application/json")
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'ObjectId' is not JSON serializable
ERROR 2018-08-24 22:35:50,013 basehttp 23830 123145566916608 "GET /view/task/5b5f02a4421aa9031208072c/ HTTP/1.1" 500 84206
WARNING 2018-08-24 22:35:50,488 base 23830 123145561661440 Not Found: /favicon.ico
WARNING 2018-08-24 22:35:50,489 basehttp 23830 123145561661440 "GET /favicon.ico HTTP/1.1" 404 3053
INFO 2018-08-24 22:39:25,743 basehttp 24024 123145450041344 "GET /view/task/5b5f02a4421aa9031208072c/ HTTP/1.1" 200 27
INFO 2018-08-24 22:40:00,898 basehttp 24069 123145605603328 "GET /view/task/5b5f02a4421aa9031208072c/ HTTP/1.1" 200 236
INFO 2018-08-24 22:48:19,998 basehttp 24116 123145527705600 "GET /view/task/5b5f02a4421aa9031208072c/ HTTP/1.1" 200 236
INFO 2018-08-24 22:48:52,623 basehttp 24116 123145527705600 "GET /showtasks/0/4/ HTTP/1.1" 200 521
INFO 2018-08-24 22:49:38,126 basehttp 24116 123145527705600 "GET /showtasks/0/4/ HTTP/1.1" 200 521
INFO 2018-08-24 22:50:54,236 basehttp 24116 123145527705600 "GET /view/task/5b5f02a4421aa9031208072c HTTP/1.1" 301 0
INFO 2018-08-24 22:51:21,525 basehttp 24116 123145527705600 "GET /view/task/5b5f02a4421aa9031208072c HTTP/1.1" 301 0
INFO 2018-08-24 22:51:26,211 basehttp 24116 123145527705600 "GET /view/task/5b5f02a4421aa9031208072c/ HTTP/1.1" 200 236
INFO 2018-08-24 22:52:12,371 basehttp 24283 123145451565056 "GET /view/task/5b5f02a4421aa9031208072c HTTP/1.1" 200 236
INFO 2018-08-24 22:52:59,348 basehttp 24283 123145451565056 "GET /showtasks/0/4 HTTP/1.1" 301 0
INFO 2018-08-24 22:53:00,761 basehttp 24283 123145451565056 "GET /showtasks/0/4 HTTP/1.1" 301 0
INFO 2018-08-24 22:53:25,868 basehttp 24283 123145451565056 "GET /showtasks/0/4 HTTP/1.1" 301 0
INFO 2018-08-24 22:53:33,919 basehttp 24283 123145451565056 "GET /showtasks/0/4/ HTTP/1.1" 200 521
INFO 2018-08-24 22:55:33,031 basehttp 24283 123145451565056 "GET /showtasks/0/4 HTTP/1.1" 301 0
INFO 2018-08-24 22:55:33,112 basehttp 24283 123145456820224 "GET /showtasks/0/4/ HTTP/1.1" 200 521
ERROR 2018-08-24 22:56:05,724 exception 24349 123145479471104 Internal Server Error: /showtasks/0/4/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bcj/Documents/科技部/EItools/EItools/crawler/task.py", line 23, in get_tasks_by_page
    tasks=mongo_client.get_all_task(int(offset),int(size))
ValueError: invalid literal for int() with base 10: '4/'
ERROR 2018-08-24 22:56:05,798 basehttp 24349 123145479471104 "GET /showtasks/0/4/ HTTP/1.1" 500 63880
ERROR 2018-08-24 22:56:15,091 exception 24349 123145484726272 Internal Server Error: /showtasks/0/4/
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 128, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bcj/Documents/科技部/EItools/EItools/crawler/task.py", line 23, in get_tasks_by_page
    tasks=mongo_client.get_all_task(int(offset),int(size))
ValueError: invalid literal for int() with base 10: '4/'
ERROR 2018-08-24 22:56:15,139 basehttp 24349 123145484726272 "GET /showtasks/0/4/ HTTP/1.1" 500 63880
INFO 2018-08-24 22:56:46,746 basehttp 24391 123145379528704 "GET /showtasks/0/4/ HTTP/1.1" 200 521
INFO 2018-08-24 22:56:52,778 basehttp 24391 123145384783872 "GET /showtasks/0/4/ HTTP/1.1" 200 521
INFO 2018-08-24 22:57:25,255 basehttp 24432 123145586974720 "GET /showtasks/0/4/ HTTP/1.1" 200 521
INFO 2018-08-24 22:58:44,002 basehttp 24432 123145586974720 "GET /showtasks/0/4/ HTTP/1.1" 200 521
INFO 2018-08-24 22:59:27,048 basehttp 24432 123145586974720 "GET /showtasks/0/4/ HTTP/1.1" 200 521
INFO 2018-08-24 23:01:03,232 task 24432 123145586974720 2
INFO 2018-08-24 23:01:03,241 basehttp 24432 123145586974720 "GET /download/crawldata/5b5f02a4421aa9031208072c/ HTTP/1.1" 200 25
INFO 2018-08-24 23:05:57,544 task 24538 123145633669120 2
INFO 2018-08-24 23:05:57,545 task 24538 123145633669120 Object of type 'ObjectId' is not JSON serializable
INFO 2018-08-24 23:05:57,546 basehttp 24538 123145633669120 "GET /download/crawldata/5b5f02a4421aa9031208072c/ HTTP/1.1" 200 25
INFO 2018-08-24 23:13:45,981 task 24639 123145436938240 2
INFO 2018-08-24 23:13:45,982 task 24639 123145436938240 Object of type 'ObjectId' is not JSON serializable
INFO 2018-08-24 23:13:45,983 basehttp 24639 123145436938240 "GET /download/crawldata/5b5f02a4421aa9031208072c/ HTTP/1.1" 200 25
INFO 2018-08-24 23:29:40,740 basehttp 24879 123145487437824 "GET /showtasks/0/4/ HTTP/1.1" 200 521
INFO 2018-08-24 23:30:41,874 task 24879 123145487437824 2
INFO 2018-08-24 23:30:41,875 basehttp 24879 123145487437824 "GET /download/crawldata/5b5f02a4421aa9031208072c/ HTTP/1.1" 200 1858
INFO 2018-08-24 23:31:09,856 task 24879 123145487437824 2
INFO 2018-08-24 23:31:09,857 basehttp 24879 123145487437824 "GET /download/crawldata/5b5f02a4421aa9031208072c/ HTTP/1.1" 200 1858
INFO 2018-08-24 23:33:41,700 task 24972 123145487290368 2
INFO 2018-08-24 23:33:41,701 basehttp 24972 123145487290368 "GET /download/crawldata/5b5f02a4421aa9031208072c/ HTTP/1.1" 200 1858
WARNING 2018-08-24 23:42:04,253 base 25178 123145431220224 Not Found: /download/crawldata/
WARNING 2018-08-24 23:42:04,255 basehttp 25178 123145431220224 "GET /download/crawldata/ HTTP/1.1" 404 3077
INFO 2018-08-24 23:42:24,235 basehttp 25178 123145431220224 "GET /download/crawldata/5b5f02a4421aa9031208072c HTTP/1.1" 301 0
INFO 2018-08-24 23:42:24,381 task 25178 123145436475392 2
INFO 2018-08-24 23:42:24,383 basehttp 25178 123145436475392 "GET /download/crawldata/5b5f02a4421aa9031208072c/ HTTP/1.1" 200 1858
